version: "3.7"
services:
  client:
    build:
      context: ./src/client
    image: gcr.io/nnyn-dev/graceful-update-test/client:0.2
  server:
    build:
      context: ./src/server
    image: gcr.io/nnyn-dev/graceful-update-test/server:0.3
