apiVersion: apps/v1
kind: Deployment
metadata:
  name: graceful-deployment
spec:
  selector:
    matchLabels:
      app: graceful
  replicas: 8
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: graceful
    spec:
      containers:
      - name: graceful
        image: gcr.io/nnyn-dev/graceful-update-test/server:0.3
        env:
          - name: NUM
            value: "15"
        lifecycle:
          preStop:
            exec:
              command:
                - "/bin/sleep"
                - "10"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
