version: "3.7"
services:
  client:
    build:
      context: ./client
    image: gcr.io/nnyn-dev/graceful-update-test/client
  server:
    build:
      context: ./server
    image: gcr.io/nnyn-dev/graceful-update-test/server
