apiVersion: apps/v1
kind: Deployment
metadata:
  name: graceful-deployment
spec:
  selector:
    matchLabels:
      app: graceful
  template:
    metadata:
      labels:
        app: graceful
    spec:
      containers:
      - name: graceful
        image: gcr.io/nnyn-dev/graceful-update-test/client:0.2
        args:
          - "-H"
          - "http://35.227.204.98"
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
